Updated version of the cppbench performance testing tool.
Minor improvements include
  - the ability to list the known test cases
  - environment variables specified in the CXXFLAGS are properly expanded

diff --git a/prototypes/cppbench b/prototypes/cppbench
--- a/prototypes/cppbench
+++ b/prototypes/cppbench
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+# Test runner for small C++ performance tests
+#
+# Author: Chris Foster [chris42f (at) gmail (dot) com]
+
 function print_help
 {
 cat <<EOF
@@ -13,88 +17,98 @@ each benchmark in the suite are displayed in human-readable format.
 
 
 Source code markup:
-	The source file contains several special comment types:
+    The source file contains several special comment types:
 
-	To specifiy lines which should be uncommented when running the
-	benchmarks name1, name2, there should be a comment of the form
+    To specifiy lines which should be uncommented when running the
+    benchmarks name1, name2, there should be a comment of the form
 
-		// code_to_run; //##bench name1 name2 ...
+        // code_to_run; //##bench name1 name2 ...
 
-	The description for a particular benchmark is of the form
+    The description for a particular benchmark is of the form
 
-		//##description name <string describing test>
+        //##description name <string describing test>
 
-	Only benchmarks with a description line are considered.
+    Only benchmarks with a description line are considered.
 
-	Finally, the compiler, compiler optimizations and linker flags are given as
-	follows:
-	//##CXX g++
-	//##CXXFLAGS -O3 ...
-	//##LDFLAGS -lm ...
+    Finally, the compiler, compiler optimizations and linker flags are given as
+    follows:
+    //##CXX g++
+    //##CXXFLAGS -O3 ...
+    //##LDFLAGS -lm ...
 
 Options:
-	-h                   This help
-	-n name1,name2,...   Specify benchmark names to run.
-	-S                   Dump assembly listings rather than running.
-	-v                   View the modified source before running the benchmark
-
-	<gcc options>
+    -h                   This help
+    -n name1,name2,...   Specify benchmark names to run.
+    -S                   Dump assembly listings rather than running.
+    -v                   View the modified source before running the benchmark
+    -l                   List the benchmark tags defined in the source
 
 EOF
 }
 
 if [[ -z $1 ]] ; then
-	print_help
-	exit -1
+    print_help
+    exit -1
 fi
 
 viewSource=0
 dumpAssembly=0
+listTags=0
 while [[ -n $1 ]] ; do
-	case $1 in
-		-n)
-			shift
-			benchmarkNamesToRun="$(echo $1 | tr ',' ' ')";;
-		-h)
-			print_help
-			exit 0;;
-		-v)
-			viewSource=1;;
-		-S)
-			dumpAssembly=1;;
-		*)
-			sourceFile=$1;;
-	esac
-	shift
+    case $1 in
+        -n)
+            shift
+            benchmarkNamesToRun="$(echo $1 | tr ',' ' ')";;
+        -h)
+            print_help
+            exit 0;;
+        -v)
+            viewSource=1;;
+        -S)
+            dumpAssembly=1;;
+        -l)
+            listTags=1;;
+        *)
+            sourceFile=$1;;
+    esac
+    shift
 done
 
 if [[ ! -f $sourceFile ]] ; then
-	echo "Source file not found" 1>&2
-	exit -1
+    echo "Source file not found" 1>&2
+    exit -1
 fi
 
 # get all the benchmark names
 benchmarkNamesAll=$(awk '/\/\/##description/ { print $2 }' $sourceFile)
 
 if [[ -z $benchmarkNamesAll ]] ; then
-	echo "No benchmarks found" 1>&2
-	exit -1
+    echo "No benchmarks found" 1>&2
+    exit -1
 fi
 
 if [[ -z $benchmarkNamesToRun ]] ; then
-	benchmarkNamesToRun="$benchmarkNamesAll"
+    benchmarkNamesToRun="$benchmarkNamesAll"
+fi
+
+if [[ $listTags == 1 ]] ; then
+    echo "Benchmark names:"
+    for tag in $benchmarkNamesAll ; do
+        echo "    $tag"
+    done
+    exit 0
 fi
 
 # get compile flags
 CXX=$(sed -n -e '/\/\/##CXX\>/ { s/\/\/##CXX\>//p ; q}' $sourceFile)
 if [[ -z $CXX ]] ; then
-	CXX=c++
+    CXX=c++
 fi
 CXXFLAGS=$(sed -n -e 's/\/\/##CXXFLAGS//p' $sourceFile)
 if [[ $dumpAssembly == 1 ]] ; then
-	CXXFLAGS="${CXXFLAGS} -S"
+    CXXFLAGS="${CXXFLAGS} -S"
 else
-	LDFLAGS=$(sed -n -e 's/\/\/##LDFLAGS//p' $sourceFile)
+    LDFLAGS=$(sed -n -e 's/\/\/##LDFLAGS//p' $sourceFile)
 fi
 
 tmpFileName=_cppbench_tmp.cpp
@@ -102,27 +116,30 @@ tmpOutName=_cppbench_tmp
 
 # Compile each benchmark.
 for name in $benchmarkNamesToRun ; do
-	notThisNameAlt="\\($(echo $benchmarkNamesAll | sed -e "s/\<$name\> *//" -e 's/ \+/\\|/g')\\)"
-	sed -e '/\/\/##bench.*\<'"$name"'\>/ {s+\(//\|/\*\|\*/\)++}' -e '/\/\/##bench.*\<'"NOT_$notThisNameAlt"'\>/ {s/\/\///}' $sourceFile > $tmpFileName
-	echo "-------------------- Benchmark: $name --------------------"
-	echo "$CXX $CXXFLAGS $sourceFile $LDFLAGS"
-	if [[ $viewSource == 1 ]] ; then
-		less $tmpFileName
-	fi
-	$CXX $CXXFLAGS $tmpFileName -o $tmpOutName $LDFLAGS
-	if [[ $? != 0 ]] ; then
-		exit -1
-	fi
-	if [[ $dumpAssembly == 1 ]] ; then
-		# Move assembly somewhere it can be viewed
-		mv $tmpOutName "${sourceFile%.cpp}.${name}.s"
-	else
-		# output description and time program run
-		echo -n "Description: "
-		sed -n -e 's/.*\/\/##description *\<'"$name"'\> *//p' $sourceFile
-		time ./$tmpOutName 2>/dev/null
-		echo
-	fi
+    notThisNameAlt="\\($(echo $benchmarkNamesAll | sed -e "s/\<$name\> *//" -e 's/ \+/\\|/g')\\)"
+    sed -e '/\/\/##bench.*\<'"$name"'\>/ {s+\(//\|/\*\|\*/\)++}' -e '/\/\/##bench.*\<'"NOT_$notThisNameAlt"'\>/ {s/\/\///}' $sourceFile > $tmpFileName
+    echo "-------------------- Benchmark: $name --------------------"
+    eval echo $CXX $CXXFLAGS $sourceFile $LDFLAGS
+    if [[ $viewSource == 1 ]] ; then
+        less $tmpFileName
+    fi
+	# Use 'eval' here so that any environment variables in $CXXFLAGS are
+	# expanded correctly.
+    eval $CXX $CXXFLAGS $tmpFileName -o $tmpOutName $LDFLAGS
+    if [[ $? != 0 ]] ; then
+        exit -1
+    fi
+    if [[ $dumpAssembly == 1 ]] ; then
+        # Move assembly somewhere it can be viewed
+        mv $tmpOutName "${sourceFile%.cpp}.${name}.s"
+        echo "generated assembly: ${sourceFile%.cpp}.${name}.s"
+    else
+        # output description and time program run
+        echo -n "Description: "
+        sed -n -e 's/.*\/\/##description *\<'"$name"'\> *//p' $sourceFile
+        time ./$tmpOutName 2>/dev/null
+        echo
+    fi
 done
 
 rm -f $tmpFileName $tmpOutName
